#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-html2haml
Version  : 2.0.0
Release  : 2
URL      : https://rubygems.org/downloads/html2haml-2.0.0.gem
Source0  : https://rubygems.org/downloads/html2haml-2.0.0.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: rubygem-html2haml-bin
BuildRequires : ruby
BuildRequires : rubygem-erubis
BuildRequires : rubygem-haml
BuildRequires : rubygem-minitest
BuildRequires : rubygem-nokogiri
BuildRequires : rubygem-rake
BuildRequires : rubygem-rdoc

%description
# Html2haml
[![Build Status](https://travis-ci.org/haml/html2haml.svg?branch=master)](https://travis-ci.org/haml/html2haml)
[![Code Climate](https://codeclimate.com/github/haml/html2haml.svg)](https://codeclimate.com/github/haml/html2haml)
[![Gem Version](https://badge.fury.io/rb/html2haml.svg)](https://rubygems.org/gems/html2haml)

%package bin
Summary: bin components for the rubygem-html2haml package.
Group: Binaries

%description bin
bin components for the rubygem-html2haml package.


%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n html2haml-2.0.0
gem spec %{SOURCE0} -l --ruby > rubygem-html2haml.gemspec

%build
gem build rubygem-html2haml.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
html2haml-2.0.0.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.2.0/cache/html2haml-2.0.0.gem
/usr/lib64/ruby/gems/2.2.0/doc/html2haml-2.0.0/ri/Html2haml/Exec/Generic/cdesc-Generic.ri
/usr/lib64/ruby/gems/2.2.0/doc/html2haml-2.0.0/ri/Html2haml/Exec/Generic/color-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/html2haml-2.0.0/ri/Html2haml/Exec/Generic/get_line-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/html2haml-2.0.0/ri/Html2haml/Exec/Generic/handle_load_error-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/html2haml-2.0.0/ri/Html2haml/Exec/Generic/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/html2haml-2.0.0/ri/Html2haml/Exec/Generic/open_file-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/html2haml-2.0.0/ri/Html2haml/Exec/Generic/parse%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/html2haml-2.0.0/ri/Html2haml/Exec/Generic/parse-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/html2haml-2.0.0/ri/Html2haml/Exec/Generic/process_result-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/html2haml-2.0.0/ri/Html2haml/Exec/Generic/puts-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/html2haml-2.0.0/ri/Html2haml/Exec/Generic/puts_action-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/html2haml-2.0.0/ri/Html2haml/Exec/Generic/set_opts-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/html2haml-2.0.0/ri/Html2haml/Exec/Generic/to_s-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/html2haml-2.0.0/ri/Html2haml/Exec/HTML2Haml/cdesc-HTML2Haml.ri
/usr/lib64/ruby/gems/2.2.0/doc/html2haml-2.0.0/ri/Html2haml/Exec/HTML2Haml/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/html2haml-2.0.0/ri/Html2haml/Exec/HTML2Haml/process_result-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/html2haml-2.0.0/ri/Html2haml/Exec/HTML2Haml/set_opts-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/html2haml-2.0.0/ri/Html2haml/Exec/cdesc-Exec.ri
/usr/lib64/ruby/gems/2.2.0/doc/html2haml-2.0.0/ri/Html2haml/HTML/ERB/add_expr_debug-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/html2haml-2.0.0/ri/Html2haml/HTML/ERB/add_expr_escaped-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/html2haml-2.0.0/ri/Html2haml/HTML/ERB/add_expr_literal-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/html2haml-2.0.0/ri/Html2haml/HTML/ERB/add_postamble-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/html2haml-2.0.0/ri/Html2haml/HTML/ERB/add_preamble-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/html2haml-2.0.0/ri/Html2haml/HTML/ERB/add_stmt-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/html2haml-2.0.0/ri/Html2haml/HTML/ERB/add_text-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/html2haml-2.0.0/ri/Html2haml/HTML/ERB/block_closer%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/html2haml-2.0.0/ri/Html2haml/HTML/ERB/block_opener%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/html2haml-2.0.0/ri/Html2haml/HTML/ERB/cdesc-ERB.ri
/usr/lib64/ruby/gems/2.2.0/doc/html2haml-2.0.0/ri/Html2haml/HTML/ERB/compile-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/html2haml-2.0.0/ri/Html2haml/HTML/ERB/h-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/html2haml-2.0.0/ri/Html2haml/HTML/ERB/has_code%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/html2haml-2.0.0/ri/Html2haml/HTML/ERB/mid_block%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/html2haml-2.0.0/ri/Html2haml/HTML/ERB/valid_ruby%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/html2haml-2.0.0/ri/Html2haml/HTML/cdesc-HTML.ri
/usr/lib64/ruby/gems/2.2.0/doc/html2haml-2.0.0/ri/Html2haml/HTML/detect_proper_parser-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/html2haml-2.0.0/ri/Html2haml/HTML/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/html2haml-2.0.0/ri/Html2haml/HTML/render-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/html2haml-2.0.0/ri/Html2haml/HTML/to_haml-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/html2haml-2.0.0/ri/Html2haml/cdesc-Html2haml.ri
/usr/lib64/ruby/gems/2.2.0/doc/html2haml-2.0.0/ri/Nokogiri/XML/CDATA/cdesc-CDATA.ri
/usr/lib64/ruby/gems/2.2.0/doc/html2haml-2.0.0/ri/Nokogiri/XML/CDATA/content_without_cdata_tokens-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/html2haml-2.0.0/ri/Nokogiri/XML/CDATA/to_haml-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/html2haml-2.0.0/ri/Nokogiri/XML/Comment/cdesc-Comment.ri
/usr/lib64/ruby/gems/2.2.0/doc/html2haml-2.0.0/ri/Nokogiri/XML/Comment/to_haml-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/html2haml-2.0.0/ri/Nokogiri/XML/DTD/cdesc-DTD.ri
/usr/lib64/ruby/gems/2.2.0/doc/html2haml-2.0.0/ri/Nokogiri/XML/DTD/to_haml-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/html2haml-2.0.0/ri/Nokogiri/XML/Document/cdesc-Document.ri
/usr/lib64/ruby/gems/2.2.0/doc/html2haml-2.0.0/ri/Nokogiri/XML/Document/to_haml-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/html2haml-2.0.0/ri/Nokogiri/XML/DocumentFragment/cdesc-DocumentFragment.ri
/usr/lib64/ruby/gems/2.2.0/doc/html2haml-2.0.0/ri/Nokogiri/XML/DocumentFragment/to_haml-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/html2haml-2.0.0/ri/Nokogiri/XML/Element/attribute_value_can_be_bare_ruby%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/html2haml-2.0.0/ri/Nokogiri/XML/Element/cdesc-Element.ri
/usr/lib64/ruby/gems/2.2.0/doc/html2haml-2.0.0/ri/Nokogiri/XML/Element/decode_entities-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/html2haml-2.0.0/ri/Nokogiri/XML/Element/dynamic_attribute%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/html2haml-2.0.0/ri/Nokogiri/XML/Element/dynamic_attributes-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/html2haml-2.0.0/ri/Nokogiri/XML/Element/haml_attribute_pair-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/html2haml-2.0.0/ri/Nokogiri/XML/Element/haml_attributes-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/html2haml-2.0.0/ri/Nokogiri/XML/Element/haml_css_attr%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/html2haml-2.0.0/ri/Nokogiri/XML/Element/render_children-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/html2haml-2.0.0/ri/Nokogiri/XML/Element/static_attribute%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/html2haml-2.0.0/ri/Nokogiri/XML/Element/static_classname%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/html2haml-2.0.0/ri/Nokogiri/XML/Element/static_id%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/html2haml-2.0.0/ri/Nokogiri/XML/Element/to_haml-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/html2haml-2.0.0/ri/Nokogiri/XML/Element/to_haml_filter-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/html2haml-2.0.0/ri/Nokogiri/XML/Node/attr_hash-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/html2haml-2.0.0/ri/Nokogiri/XML/Node/cdesc-Node.ri
/usr/lib64/ruby/gems/2.2.0/doc/html2haml-2.0.0/ri/Nokogiri/XML/Node/converted_to_haml-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/html2haml-2.0.0/ri/Nokogiri/XML/Node/erb_to_interpolation-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/html2haml-2.0.0/ri/Nokogiri/XML/Node/parse_text-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/html2haml-2.0.0/ri/Nokogiri/XML/Node/parse_text_with_interpolation-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/html2haml-2.0.0/ri/Nokogiri/XML/Node/process_inline_nodes-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/html2haml-2.0.0/ri/Nokogiri/XML/Node/tabulate-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/html2haml-2.0.0/ri/Nokogiri/XML/Node/to_haml-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/html2haml-2.0.0/ri/Nokogiri/XML/Node/uninterp-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/html2haml-2.0.0/ri/Nokogiri/XML/NodeSet/cdesc-NodeSet.ri
/usr/lib64/ruby/gems/2.2.0/doc/html2haml-2.0.0/ri/Nokogiri/XML/NodeSet/to_haml-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/html2haml-2.0.0/ri/Nokogiri/XML/ProcessingInstruction/cdesc-ProcessingInstruction.ri
/usr/lib64/ruby/gems/2.2.0/doc/html2haml-2.0.0/ri/Nokogiri/XML/ProcessingInstruction/to_haml-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/html2haml-2.0.0/ri/Nokogiri/XML/cdesc-XML.ri
/usr/lib64/ruby/gems/2.2.0/doc/html2haml-2.0.0/ri/Nokogiri/cdesc-Nokogiri.ri
/usr/lib64/ruby/gems/2.2.0/doc/html2haml-2.0.0/ri/Object/cdesc-Object.ri
/usr/lib64/ruby/gems/2.2.0/doc/html2haml-2.0.0/ri/cache.ri
/usr/lib64/ruby/gems/2.2.0/gems/html2haml-2.0.0/.gitignore
/usr/lib64/ruby/gems/2.2.0/gems/html2haml-2.0.0/.travis.yml
/usr/lib64/ruby/gems/2.2.0/gems/html2haml-2.0.0/.yardopts
/usr/lib64/ruby/gems/2.2.0/gems/html2haml-2.0.0/Changelog.markdown
/usr/lib64/ruby/gems/2.2.0/gems/html2haml-2.0.0/Gemfile
/usr/lib64/ruby/gems/2.2.0/gems/html2haml-2.0.0/MIT-LICENSE
/usr/lib64/ruby/gems/2.2.0/gems/html2haml-2.0.0/README.md
/usr/lib64/ruby/gems/2.2.0/gems/html2haml-2.0.0/Rakefile
/usr/lib64/ruby/gems/2.2.0/gems/html2haml-2.0.0/bin/html2haml
/usr/lib64/ruby/gems/2.2.0/gems/html2haml-2.0.0/html2haml.gemspec
/usr/lib64/ruby/gems/2.2.0/gems/html2haml-2.0.0/lib/html2haml.rb
/usr/lib64/ruby/gems/2.2.0/gems/html2haml-2.0.0/lib/html2haml/exec.rb
/usr/lib64/ruby/gems/2.2.0/gems/html2haml-2.0.0/lib/html2haml/html.rb
/usr/lib64/ruby/gems/2.2.0/gems/html2haml-2.0.0/lib/html2haml/html/erb.rb
/usr/lib64/ruby/gems/2.2.0/gems/html2haml-2.0.0/lib/html2haml/version.rb
/usr/lib64/ruby/gems/2.2.0/gems/html2haml-2.0.0/test/erb_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/html2haml-2.0.0/test/html2haml_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/html2haml-2.0.0/test/jruby/erb_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/html2haml-2.0.0/test/jruby/html2haml_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/html2haml-2.0.0/test/test_helper.rb
/usr/lib64/ruby/gems/2.2.0/specifications/html2haml-2.0.0.gemspec

%files bin
%defattr(-,root,root,-)
/usr/bin/html2haml
