#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-html2haml
Version  : 2.0.0
Release  : 3
URL      : https://rubygems.org/downloads/html2haml-2.0.0.gem
Source0  : https://rubygems.org/downloads/html2haml-2.0.0.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: rubygem-html2haml-bin
BuildRequires : ruby
BuildRequires : rubygem-erubis
BuildRequires : rubygem-haml
BuildRequires : rubygem-minitest
BuildRequires : rubygem-nokogiri
BuildRequires : rubygem-rake
BuildRequires : rubygem-rdoc

%description
# Html2haml
[![Build Status](https://travis-ci.org/haml/html2haml.svg?branch=master)](https://travis-ci.org/haml/html2haml)
[![Code Climate](https://codeclimate.com/github/haml/html2haml.svg)](https://codeclimate.com/github/haml/html2haml)
[![Gem Version](https://badge.fury.io/rb/html2haml.svg)](https://rubygems.org/gems/html2haml)

%package bin
Summary: bin components for the rubygem-html2haml package.
Group: Binaries

%description bin
bin components for the rubygem-html2haml package.


%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n html2haml-2.0.0
gem spec %{SOURCE0} -l --ruby > rubygem-html2haml.gemspec

%build
gem build rubygem-html2haml.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
html2haml-2.0.0.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/html2haml-2.0.0.gem
/usr/lib64/ruby/gems/2.3.0/gems/html2haml-2.0.0/.gitignore
/usr/lib64/ruby/gems/2.3.0/gems/html2haml-2.0.0/.travis.yml
/usr/lib64/ruby/gems/2.3.0/gems/html2haml-2.0.0/.yardopts
/usr/lib64/ruby/gems/2.3.0/gems/html2haml-2.0.0/Changelog.markdown
/usr/lib64/ruby/gems/2.3.0/gems/html2haml-2.0.0/Gemfile
/usr/lib64/ruby/gems/2.3.0/gems/html2haml-2.0.0/MIT-LICENSE
/usr/lib64/ruby/gems/2.3.0/gems/html2haml-2.0.0/README.md
/usr/lib64/ruby/gems/2.3.0/gems/html2haml-2.0.0/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/html2haml-2.0.0/bin/html2haml
/usr/lib64/ruby/gems/2.3.0/gems/html2haml-2.0.0/html2haml.gemspec
/usr/lib64/ruby/gems/2.3.0/gems/html2haml-2.0.0/lib/html2haml.rb
/usr/lib64/ruby/gems/2.3.0/gems/html2haml-2.0.0/lib/html2haml/exec.rb
/usr/lib64/ruby/gems/2.3.0/gems/html2haml-2.0.0/lib/html2haml/html.rb
/usr/lib64/ruby/gems/2.3.0/gems/html2haml-2.0.0/lib/html2haml/html/erb.rb
/usr/lib64/ruby/gems/2.3.0/gems/html2haml-2.0.0/lib/html2haml/version.rb
/usr/lib64/ruby/gems/2.3.0/gems/html2haml-2.0.0/test/erb_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/html2haml-2.0.0/test/html2haml_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/html2haml-2.0.0/test/jruby/erb_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/html2haml-2.0.0/test/jruby/html2haml_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/html2haml-2.0.0/test/test_helper.rb
/usr/lib64/ruby/gems/2.3.0/specifications/html2haml-2.0.0.gemspec

%files bin
%defattr(-,root,root,-)
/usr/bin/html2haml
